name: elfrieda.zulauf
description: Advanced
version: 0.0.1
author: 0xlzhchj.48wdqkai@vcxpu9lb.com
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines:
  pipelines/Jimmie_Grant_PhDOlive_HoylDevona_Mraz:
    name: Jimmie_Grant_PhDOlive_HoylDevona_Mraz
    description: null
    author: 0xlzhchj.48wdqkai@vcxpu9lb.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2026-02-27 18:45:52'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/Helena_Crist_IVKent_CookMs__Boris_Corkery:
    name: Helena_Crist_IVKent_CookMs__Boris_Corkery
    description: null
    author: 0xlzhchj.48wdqkai@vcxpu9lb.com
    mode: batch
    artefactID: ''
    language: sql
    createdAt: '2026-02-27 18:45:54'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-02-27 18:45:44'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: 0xlzhchj.48wdqkai@vcxpu9lb.com
  createdAt: '2026-02-27 18:45:44'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
